---
apiVersion: v1
kind: Service
metadata:
  name: inference
  namespace: mlops-staging
  labels:
    app: inference
    environment: staging
spec:
  type: ClusterIP
  selector:
    app: inference
    environment: staging
  ports:
    - name: http
      port: 80
      targetPort: 8000
      protocol: TCP
