---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: inference
  namespace: mlops-staging
  labels:
    release: kube-prometheus-stack
    app: inference
    environment: staging
spec:
  selector:
    matchLabels:
      app: inference
      environment: staging
  namespaceSelector:
    matchNames:
      - mlops-staging
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
      honorLabels: true
