---
extends: default

rules:
  line-length:
    max: 200
    level: warning
  document-start:
    present: false
  truthy:
    check-keys: false
  indentation:
    spaces: 2
    indent-sequences: consistent
  comments:
    min-spaces-from-content: 1
  braces:
    max-spaces-inside: 1
  brackets:
    max-spaces-inside: 1

ignore: |
  .venv/
  deploy/monitoring/grafana-dashboards.yaml
