FROM python:3.13

RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential \
        curl \
        wget \
        git \
        vim \
        libglib2.0-0 \
        libsm6 \
        libxrender1 \
        libxext6 \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Python-залежності
COPY requirements.txt /app/requirements.txt
RUN pip install --no-cache-dir --upgrade pip \
    && pip install --no-cache-dir -r /app/requirements.txt

# Код і модель
COPY app/         /app/app/
COPY model/       /app/model/
COPY export_model.py /app/export_model.py

ENTRYPOINT ["python", "app/inference.py"]
