---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlops-inference-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/bbeellkk-ua/goit-mlops.git
    targetRevision: final
    path: deploy/inference-staging
  destination:
    server: https://kubernetes.default.svc
    namespace: mlops-staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
